// pages/terms.js
import LegalLayout from '../components/LegalLayout';

export default function TermsOfServicePage() {
  return (
    <LegalLayout title="Terms of Service">
      <p>**Ikigai Journey** — a product of Purposely Learning Hub</p>
      <p>Last updated: August 20, 2026</p>
      <h2>1. Acceptance of Terms</h2>
      <p>By accessing or using app.purposelylearning.com (the "Service"), you agree to be bound by these Terms of Service. If you do not agree, please do not use the Service.</p>
      <h2>2. Description of the Service</h2>
      <p>Ikigai Journey is a guided, AI-assisted self-discovery experience. You answer 16 questions across four sections; the free preview covers Section 1 (Questions 1–4). Continuing beyond the free preview requires a one-time payment. Upon completion, you receive a personalized 20-section report ("Report") generated using artificial intelligence based on your answers, delivered via the web app and by email.</p>
      <h2>3. Eligibility</h2>
      <p>You must be at least 18 years old, or the age of majority in your jurisdiction, to purchase and use the paid portion of this Service.</p>
      <h2>4. Payment</h2>
      <ul>
      <li>The current price is displayed at checkout and is charged once, in Philippine Pesos (PHP), via PayMongo.</li>
      <li>Payment grants you access to complete the full 16-question journey and receive your Report for that session.</li>
      <li>Discount codes, where offered, are applied at our sole discretion and may be modified or discontinued at any time.</li>
      <li>All payments are processed by PayMongo. We do not store your payment card, GCash, or bank account details.</li>
      </ul>
      <h2>5. Refund Policy</h2>
      <p>**All sales are final. We do not offer refunds once payment has been made and access to the full journey has been granted**, regardless of whether you complete the journey or use the generated Report. Please review the free preview (Section 1) carefully before deciding to purchase, as it is designed to give you a genuine sense of the experience and depth of the full journey.</p>
      <p>If you believe you were charged in error (e.g., duplicate charge, unauthorized transaction), message us on Facebook or Instagram within 7 days of the transaction, and we will review the matter in good faith.</p>
      <h2>6. Nature of the Report</h2>
      <p>Your Report is generated by an artificial intelligence system based on the answers you provide. It is intended for **personal reflection, motivation, and general guidance only**. It does not constitute professional financial, legal, psychological, medical, career, or business advice. You should not rely on the Report as a substitute for advice from a qualified professional in any relevant field. Decisions you make based on the Report are your own responsibility.</p>
      <h2>7. Accuracy and Limitations</h2>
      <p>We do not guarantee that the Report will be accurate, complete, or suited to your particular circumstances. The quality and usefulness of your Report depends significantly on the depth and honesty of the answers you provide. AI-generated content may occasionally contain errors, generalizations, or inconsistencies.</p>
      <h2>8. User Conduct</h2>
      <p>You agree not to:</p>
      <ul>
      <li>Use the Service for any unlawful purpose</li>
      <li>Attempt to bypass payment or access controls</li>
      <li>Misrepresent your identity or provide false information to obtain unauthorized access</li>
      <li>Reproduce, resell, or redistribute the Service or Reports generated by other users</li>
      </ul>
      <h2>9. Intellectual Property</h2>
      <p>The Service, including its design, questions, branding (Ikigai Journey, Purposely Learning Hub, the Yotsuba Petal Mark), and underlying technology, is owned by Purposely Learning Hub. Your Report is generated specifically for you based on your answers; you may use your own Report for personal purposes.</p>
      <h2>10. Third-Party Services</h2>
      <p>The Service relies on third-party providers, including PayMongo (payments), Anthropic (AI report generation), Resend (email delivery), Supabase (data storage), and Vercel (hosting). We are not responsible for outages, errors, or issues arising from these third-party services, though we will make reasonable efforts to resolve any disruption to your experience.</p>
      <h2>11. Limitation of Liability</h2>
      <p>To the fullest extent permitted by law, Purposely Learning Hub shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Service, including but not limited to decisions made based on your Report. Our total liability for any claim arising from the Service shall not exceed the amount you paid for the Service.</p>
      <h2>12. Changes to the Service and Terms</h2>
      <p>We may modify, suspend, or discontinue the Service, or update these Terms, at any time. Continued use of the Service after changes constitutes acceptance of the updated Terms.</p>
      <h2>13. Governing Law</h2>
      <p>These Terms are governed by the laws of the Republic of the Philippines. Any disputes shall be subject to the exclusive jurisdiction of the courts of Laguna, Philippines.</p>
      <h2>14. Contact Us</h2>
      <p>Purposely Learning Hub</p>
      <p>294 Purok 5 Majada Out, Calamba City, Laguna, 4027, Philippines</p>
      <ul>
      <li>Facebook: facebook.com/profile.php?id=61592202830156</li>
      <li>Instagram: @purposely.life</li>
      </ul>
      <hr/>
      <p className="disclaimer">This document is a draft and should be reviewed by a licensed Philippine attorney before publication.</p>
    </LegalLayout>
  );
}
